project_root <- here::here()
data_root <- here::here("data")
data_raw <- fs::path(data_root, "raw")
analysis_root <- here::here("analysis")
figures_folder <- fs::path(analysis_root, "figures")
tables_folder <- fs::path(analysis_root, "tables")
pdfs_folder <- fs::path(analysis_root, "pdfs")
reports_folder <- fs::path(analysis_root, "reports")
munge_root <- here::here("munge")
munge_R <- fs::path(munge_root, "R_script")
munge_stata <- fs::path(munge_root, "stata_do")
presentations_root <- here::here("presentations")
r_objects_folder <- here::here("R")
support_files <- here::here("support_files")
